### ISSUE TITLE
De Jenkins instantie voor CI/CD geeft te veel overhead

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/ZDS2.0#576]
# Impediment

Onze CI/CD pipeline maakt gebruik van Jenkins, meer bepaald https://jenkins.nlx.io. Het idee is dat dit 1x ingericht wordt en je er verder op kan vertrouwen om jobs op de achtergrond uit te voeren.

Echter, dit gaat de laatste tijd te veel fout. Harde schijf die volloopt, nodes die plots weer offline zijn, builds die uit het niets falen op de Github integratie... Dit brengt veel frustratie mee voor developers (Joeri en mij in dit geval) en zorgt ervoor dat we best wat nuttige tijd verspillen aan infrastructuur.

Mijn voorstel is dan ook om voor de CI doeleinden van Travis gebruik te maken in plaats van Jenkins. Travis is gratis voor open source projecten en draait op hosted infrastructuur. Onze ervaring is dat je er minder omzien naar hebt.

**Comment by TCIMEddy** [comment]
@ehotting Ik ben inhoudelijk geen specialist maar het voorstel van Sergei klinkt plausibel. Akkoord?

**Comment by TCIMEddy** [comment]
@Hugo-ter-Doest wat mij betreft volgen we advies Sergei

**Comment by TCIMEddy** [comment]
@sergei-maertens Is dit nog steeds impediment?

**Comment by sergei-maertens** [comment]
Bart heeft de schijfruimte vergroot, ik denk dat we daardoor wel even vooruit kunnen.
